---
- name: Configure hosts.allow
  become: true
  ansible.builtin.template:
    src: /tmp/konstruktoid.hardening/templates/etc/hosts.allow.j2
    dest: /etc/hosts.allow
    backup: true
    mode: "0644"
    owner: root
    group: root

- name: Configure hosts.deny
  become: true
  ansible.builtin.template:
    src: /tmp/konstruktoid.hardening/templates/etc/hosts.deny.j2
    dest: /etc/hosts.deny
    backup: true
    mode: "0644"
    owner: root
    group: root
